# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gheras' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gheras
pod 'GoogleMaps' , '4.0.0'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
end
